### ISSUE TITLE
Terminal output to serial

### ISSUE THREAD

**Issue by benjamink** [guidol70/RunCPM_RPi_Pico#3]
Is it possible to output the terminal to serial port instead of (or in addition to) USB?  I’d like to hook this up to a DEC VT510.

**Comment by guidol70** [comment]
Hi Benjamin,
sure its possible ;)
You have to replace all Serial. commands with Serial1. commands and define in the .ino the Pins.

As attachment I replaced for you Serial. (in all tab-files) with Serial1. and the serial Portr is defined for Pin1 (GPIO0) and Pin2 (GPIO1) in the .ino:

 **Serial Port Definition
  Serial =USB / Serial1 =UART0/COM1 / Serial2 =UART1/COM2**

   Serial1.setRX(1); // Pin 2 (GPIO1)
   Serial1.setTX(0); // Pin 1 (GPIO0)

   Serial2.setRX(5); // Pin 7
   Serial2.setTX(4); // Pin 6
```

[RunCPM_v6_1_Pico_Serial1_28092023.zip](https://github.com/guidol70/RunCPM_RPi_Pico/files/12777441/RunCPM_v6_1_Pico_Serial1_28092023.zip)

**Comment by benjamink** [comment]
That makes sense!  However, I'm not very experienced with building Pico projects from scratch.  I installed the appropriate board & the SDfat library into my Arduino IDE but the compile fails with the attached log output.  Ideas?

[runcpm_pico_build_errors.txt](https://github.com/guidol70/RunCPM_RPi_Pico/files/12782021/runcpm_pico_build_errors.txt)

**Comment by guidol70** [comment]
>  but the compile fails with the attached log output. Ideas?
> 

Dear Benjamin,
Yes - I have  ;)
when you check the Serction "[SdFat library change](https://github.com/MockbaTheBorg/RunCPM#sdfat-library-change)"
or the [Issue-page 143](https://github.com/MockbaTheBorg/RunCPM/issues/143)
of the original RunCPM-Github-Page then you will find a Info to change the content of the SDFatConfig.h of you SdFat-Library
(which is at C:\Users\guido\Documents\Arduino\libraries\SdFat\src\SDFatConfig.h)

This change will prevent the File32-Error while compiling.

As attachmend the zipped SDFatConfig.h and as second attachment the binary serial1-Version as .UF2 (flash on the Pico via the Boot-Button) ;)

Kind regards
Guido

[SdFatConfig.zip](https://github.com/guidol70/RunCPM_RPi_Pico/files/12784059/SdFatConfig.zip)

[RunCPM_v6_1_Pico_Serial1_28092023.zip](https://github.com/guidol70/RunCPM_RPi_Pico/files/12784067/RunCPM_v6_1_Pico_Serial1_28092023.zip)

**Comment by benjamink** [comment]
This worked great!  I need to sort out some power & connection issues but I was able to make it work successfully a couple times so this is exactly what I wanted!   Thank you!

**Comment by benjamink** [comment]
I _ALMOST_ have this working the way I want!  I have one strange remaining problem that you may know the answer to.  If I have the Pico connected via USB to my computer with minicom running & connected to the USB serial device everything works perfectly.  The RunCPM input/output all happens over the UART0 on the Pico to the VT510 as expected.

However, if I power the Pico with a power-only USB cable (eg, charger cable) without the computer involved all I get is a single garbage character on the VT510 screen.  

It seems like minicom on the PC is causing the serial connection to appear ready but the Pico is not doing that by itself.  All I have connected for the VT510 is RX/TX & ground via a MAX3232 level shifter.

Does all that make sense?  Any ideas how I can make the Pico communicate with the VT510 without the USB serial connection?

**Comment by guidol70** [comment]
> However, if I power the Pico with a power-only USB cable (eg, charger cable) without the computer involved all I get is a single garbage character on the VT510 screen.
> 
> Does all that make sense? Any ideas how I can make the Pico communicate with the VT510 without the USB serial connection?

If you only get the single char, check if the Pico is blinking - because that means he is waiting for a serial connection.
There is a routine (which I (may) have forgot to change to Serial1) in the .ino (Line 108-114):

 ```
 Serial1.begin(SERIALSPD);
  while (!Serial) {	// Wait until serial is connected
    digitalWrite(LED, HIGH^LEDinv);
    delay(sDELAY);
    digitalWrite(LED, LOW^LEDinv);
    delay(DELAY);
  }
```
The !Serial should also be !Serial1 or you do delete this routine to let the Pico directly start the serial output.

Sorry for that :(

**Comment by benjamink** [comment]
I found that & made the change but I'm having troubles compiling.  I suspect I'm missing something.  I'm trying to compile in the Arduino IDE (v1.8.19): 

```
'class arduino::UART' has no member named 'setRX'
```

**Comment by guidol70** [comment]
> I found that & made the change but I'm having troubles compiling. I suspect I'm missing something. I'm trying to compile in the Arduino IDE (v1.8.19):
> 
> ```
> 'class arduino::UART' has no member named 'setRX'
> ```

Sounds/looks like your Board-Selection isnt the [RP2040-Arduino-Core](https://github.com/earlephilhower/arduino-pico) anymore.

I also using the Arduino-IDE 1.8.19 and when dealing with differnet boards any sketches I have to reconfigure the complete Destination-board in the Tools setting like at the attched picture (which did so compile fine for me):

![Select_Pico_RP2040](https://github.com/guidol70/RunCPM_RPi_Pico/assets/5121124/6cb0fbb1-74bf-4c1d-83e0-8aff301589ad)

But for testing I recompiled it for you with the !Serial1 setting:

[RunCPM_v6_1_Pico_Serial1_28092023_2nd.zip](https://github.com/guidol70/RunCPM_RPi_Pico/files/12806629/RunCPM_v6_1_Pico_Serial1_28092023_2nd.zip)


Kind regards
Guido

**Comment by benjamink** [comment]
Thanks!  I was missing the "Additional Boards" URL in the preferences.

**Comment by benjamink** [comment]
Just wanted to say one last(?) thanks with some pictures!

![image](https://github.com/guidol70/RunCPM_RPi_Pico/assets/1457764/4b0fc760-bd08-44d0-8794-0e323908ac34)
![image](https://github.com/guidol70/RunCPM_RPi_Pico/assets/1457764/32c209c7-1b8b-4f56-be4c-cf295eda4ad0)
![image](https://github.com/guidol70/RunCPM_RPi_Pico/assets/1457764/3e96e624-0d3b-4ecb-a95b-b1e5de7dc07e)
